version: '3.1'
services:
  inventory-db:
    image: postgres
    environment:
      - POSTGRES_USER=orders
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=orders
    ports:
      - "5431:5432" #hostport:containerport